### ISSUE TITLE
3D-PACK

### ISSUE THREAD

**Issue by XKMEXX** [YanWenKun/ComfyUI-Windows-Portable#10]
![image](https://github.com/user-attachments/assets/3d9867be-4d02-4da8-8f9f-33487dbfab6d)
![image](https://github.com/user-attachments/assets/c30d309e-822d-4ca5-bd37-d0df1c249ef7)

Hello, none of the workflows that are in the 3d-pack folder work

**Comment by YanWenKun** [comment]
The 3D-Pack is not loaded at all. Try using the clean package and do not update the custom nodes.

If that's not the case, it may be a compatibility issue, and would need detailed logs to debug with.

**Comment by RegRurutu** [comment]
7.8 seconds (IMPORT FAILED): E:\AI\ComfyUI-3d-pack\ComfyUI\custom_nodes\ComfyUI-3D-Pack

everything is loading fine except ComfyUI-3d-pack
running CUDA 12.6 on windows
Any hints to make 3d-pack to work ?

**Comment by YanWenKun** [comment]
@RegRurutu Need detailed log. You can try move all folders except 3D-Pack in `custom_nodes` to somewhere else, or just disable them in Manager. So they won't be loaded, and it will be easier to debug with.
