### ISSUE TITLE
Unable to update ComfyUI

### ISSUE THREAD

**Issue by ChrisTheDBA** [YanWenKun/ComfyUI-Windows-Portable#11]
On the 7/28 release. 

using update_comfyui.bat 
```
Traceback (most recent call last):
  File "D:\comfyui2\comfyui_windows_portable\update\update.py", line 76, in <module>
    pull(repo)
  File "D:\comfyui2\comfyui_windows_portable\update\update.py", line 13, in pull
    merge_result, _ = repo.merge_analysis(remote_master_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pygit2.GitError: object not found - no match for id (f82d09c9b40fd9ebbc080bc5662ddb39787b1ec9)
```

Using GUI:
```
Update ComfyUI
Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v -- origin
  stderr: 'error: Could not read f82d09c9b40fd9ebbc080bc5662ddb39787b1ec9
error: Could not read f82d09c9b40fd9ebbc080bc5662ddb39787b1ec9
error: Could not read f82d09c9b40fd9ebbc080bc5662ddb39787b1ec9
error: Could not read f82d09c9b40fd9ebbc080bc5662ddb39787b1ec9
fatal: refusing to merge unrelated histories'
CUSTOM NODE PULL: Fail
```

**Comment by YanWenKun** [comment]
This is caused by merge conflict, possibly related to the commit node of ComfyUI (e.g. force-push that overwrites exist commits).
I will add a force-update script in the future for situation like this.

For now, you can force update ComfyUI using this method (via cmd/powershell/git bash):

```
cd PATH\TO\ComfyUI
git pull --force
```

**Comment by 7nhdung** [comment]
![Error_Updating_ComfyUI_YanWenKun](https://github.com/user-attachments/assets/427b231a-1c79-4a6e-9518-04e9bdab8932)

Sorry! I get the same problem when run update_comfyui.bat. And when I follow your instruction: in the ComfyUI directory, I type git pull --force > and it displays an error: Could not read ....... Could not parse commit ..... .(error screenshot include). 

Please help me. Thanks advance

**Comment by YanWenKun** [comment]
@7nhdung 
Try this:
```
git fetch --unshallow
```
Then
```
git pull --force
```

**Comment by ChrisTheDBA** [comment]
since we have a new version, this can be closed.

**Comment by ChrisTheDBA** [comment]
Can I close it?
