### ISSUE TITLE
3D PACK

### ISSUE THREAD

**Issue by yuzehong1986** [YanWenKun/ComfyUI-Windows-Portable#12]
Versions | 版本信息
Python 3.11
CUDA 12.1
PyTorch 2.3.0
xFormers 0.0.26.post1
用的这一版的。解压后打开报错。

F:\webui\ComfyUI_Windows_portable>rem set PATH=C:\Program Files\Oculus\Support\oculus-runtime;c:\Users\Administrator\AppData\Local\Programs\Cursor\resources\app\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE;D:\Main_Data\16_____soft\cmake-3.26.0-rc4-windows-x86_64\bin;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\Main_Data\translate\ffmpeg-master-latest-win64-gpl\bin;C:\Users\Administrator\.dotnet\tools;c:\Users\Administrator\AppData\Local\Programs\Cursor\resources\ap;C:\Program Files\Calibre2\;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python310\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\Main_Data\translate\ffmpeg-master-latest-win64-gpl\bin;C:\Users\Administrator\.dotnet\tools;C:\Users\Administrator\AppData\Local\Programs\Ollama;;C:\EDIT_THIS_TO_PATH_TO_YOUR_\python_embeded\Scripts\

F:\webui\ComfyUI_Windows_portable>rem set HTTP_PROXY=http://localhost:1081

F:\webui\ComfyUI_Windows_portable>rem set HTTPS_PROXY=http://localhost:1081

F:\webui\ComfyUI_Windows_portable>rem set PYTHONPYCACHEPREFIX=.\pycache

F:\webui\ComfyUI_Windows_portable>rem .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --disable-auto-launch

F:\webui\ComfyUI_Windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-01 16:42:02.127791
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: F:\webui\ComfyUI_Windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\webui\ComfyUI_Windows_portable\ComfyUI
** Log path: F:\webui\ComfyUI_Windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   2.6 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24563 MB, total RAM 65345 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: F:\webui\ComfyUI_Windows_portable\ComfyUI\web
Warn!: xFormers is available (Attention)
Warn!: Traceback (most recent call last):
  File "F:\webui\ComfyUI_Windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 47, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 78, in <module>
    from Unique3D.scripts.project_mesh import multiview_color_projection, get_cameras_list
  File "F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 98, in <module>
    pix2faces_renderer = Pix2FacesRenderer()
                         ^^^^^^^^^^^^^^^^^^^
  File "F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\Unique3D\scripts\project_mesh.py", line 70, in __init__
    self._glctx = dr.RasterizeGLContext(output_db=False, device=device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\webui\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
                       ^^^^^^^^^^^^^^^^^^^^
  File "F:\webui\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\nvdiffrast\torch\ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "F:\webui\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "F:\webui\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "F:\webui\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1802, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "F:\webui\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1851, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

Warn!: Cannot import F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: Ninja is required to load C++ extensions
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['F:\\webui\\ComfyUI_Windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'F:\\webui\\ComfyUI_Windows_portable\\ComfyUI\\models\\animatediff_models']
[Crystools INFO] Crystools version: 1.15.0
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i9-13900KF - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090
[Crystools INFO] NVIDIA Driver: 560.94
### ComfyUI-Impact-Pack: Updating dependencies [0 -> 22]

[bold yellow]WARN: The `COMFYUI_PATH` environment variable is not set. Assuming `F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack/../../` as the ComfyUI path.[/bold yellow]

[bold yellow]WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `F:\webui\ComfyUI_Windows_portable\ComfyUI\models` as the ComfyUI path.[/bold yellow]
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['F:\\webui\\ComfyUI_Windows_portable\\python_embeded\\python.exe', 'install.py'] in 'F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.82.5)
Total VRAM 24563 MB, total RAM 65345 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### ComfyUI Revision: 1 [93000580] | Released on '2024-07-27'
A new version of Albumentations is available: 1.4.14 (you have 1.4.12). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
[ReActor] - STATUS - Running v0.5.1-a6 in ComfyUI
Torch version: 2.3.0+cu121
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
A new version of Albumentations is available: 1.4.14 (you have 1.4.12). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
FizzleDorf Custom Nodes: Loaded
[comfy_mtb] | INFO -> loaded 78 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

[rgthree] Loaded 40 extraordinary nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: Created default conf file at `F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 217 nodes successfully.

        "The future depends on what you do today." - Mahatma Gandhi

Import times for custom nodes:
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools-save
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfyui-portrait-master
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.1 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.1 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved
   0.1 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.2 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.3 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.3 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.6 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   1.2 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   1.3 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   1.6 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.7 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   2.4 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   3.6 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   7.1 seconds: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
  27.0 seconds (IMPORT FAILED): F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\custom-node-list.json [DONE]
FETCH DATA from: F:\webui\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\github-stats.json [DONE]

**Comment by yuzehong1986** [comment]
![image](https://github.com/user-attachments/assets/543af3cf-4dda-46d0-a587-229ba06cc3cb)
VS2022这个已经安装

**Comment by yuzehong1986** [comment]
我还有一个comfyui，会不会相互冲突？

**Comment by YanWenKun** [comment]
> 我还有一个comfyui，会不会相互冲突？

不会，这个包使用自带的 Python Lib 

根据你发的日志，正常启动了，但是3D-Pack没加载成功，问题是没有找到 Ninja

```
Ninja is required to load C++ extensions
```

其实这个包里自带了 Ninja ，但需要添加到执行路径里。方法如下：

1. 编辑 `run_nvidia_gpu.bat`

2. 找到：

```
rem set PATH=%PATH%;C:\EDIT_THIS_TO_PATH_TO_YOUR_\python_embeded\Scripts\
```

将 `rem ` （注释） 去掉，并把 `C:\EDIT_THIS_TO_PATH_TO_YOUR_\` 编辑为 `F:\webui\ComfyUI_Windows_portable\` ，
再运行即可。

之后我会考虑换一个新的启动脚本，以免再出现类似问题

**Comment by yuzehong1986** [comment]
收到！谢谢！
