### ISSUE TITLE
Entry point could not be loacate

### ISSUE THREAD

**Issue by 7nhdung** [YanWenKun/ComfyUI-Windows-Portable#13]
![Error_Python Entry Point Not Found](https://github.com/user-attachments/assets/c3b3d896-0dff-4ebc-ba2a-fc277e3a8f1b)
When I installing a new fresh ComfyUI , it displays "Python - Entry Point Not Found" as the screenshot above.
How do I fix it? Thanks

**Comment by YanWenKun** [comment]
The message is about missing CUDA. You can try install the full CUDA Toolkit and see if it works:

https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

Installing the latest version 12.6 is totally fine, it's compatible with Comfy's 12.1 or 12.4
