### ISSUE TITLE
内置的3D-Pack部分缺少NeuS

### ISSUE THREAD

**Issue by Haojie99** [YanWenKun/ComfyUI-Windows-Portable#22]
打开一个有NeuS的3D-workflow之后，提示缺少NeuS，用ComfyUI-Manager无法修复，应该是3D-Pack原作者更新过版本，不知道现在去哪里可以补充这个缺失的NeuS部分呢？打扰
![image](https://github.com/user-attachments/assets/bd1f087e-f932-4901-b2ef-6b1616382715)
![image](https://github.com/user-attachments/assets/9e974a15-ed61-4785-9cba-dd8be1045963)

**Comment by Haojie99** [comment]
![image](https://github.com/user-attachments/assets/14607f51-e96c-4ec9-b1c9-2aa2690a24df)

**Comment by YanWenKun** [comment]
一定要用NeuS的话，考虑把3D-Pack `git reset --hard` 到[6月23号](https://github.com/MrForExample/ComfyUI-3D-Pack/tree/3b4e715939376634c68aa4c1c7d4ea4a8665c098)的版本。但同时也要降级PyTorch到2.2.2

或者用我的整合包，[7月1号](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.10)版本应该刚好（也难怪emoji最多）

**Comment by Haojie99** [comment]
感谢大佬回复，版本是确实是老师给的较早的工作流。试了一下大佬的7/1版本，发现直接run.gpu.bat后manager会显示3D-Pack import failed

**Comment by YanWenKun** [comment]
导入失败得看详细的错误日志了，或者用更早的版本试试，比如 [05/21](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.9)

**Comment by YanWenKun** [comment]
对了，有 Docker/Podman 环境的话，试试这个：
https://github.com/YanWenKun/ComfyUI-Docker/blob/main/comfy3d-pt22/README.zh.adoc
