### ISSUE TITLE
Can't you make a separate version of the 3D pack models that I put in myself?

### ISSUE THREAD

**Issue by taejinSong** [YanWenKun/ComfyUI-Windows-Portable#31]
I would like to say thank you for making the execution even testable.
I tried to use the official 3D pack version, but I was so happy to find Yan WenKun's ComplyUI and even Preview 3D came out
Whenever I try to run a 3D pack workflow, I am always stuck here in ".cache/huggingface/downloae/xx.metadata" except for one or two workflows.
If I can download it and put it in the folder myself, I think it will run, is it impossible?

**Comment by YanWenKun** [comment]
Exactly what I want!
Downloading models through `huggingface-cli` into `.cache` was so inconvenient. I'm working on it to find an alternative.

**Comment by YanWenKun** [comment]
It turns out to be easy... Just add env var `set HF_HUB_CACHE=%~dp0\HuggingFaceHub` in `run_nvidia_gpu.bat`.

I'm adding this to start script in the new version.

**Comment by YanWenKun** [comment]
The new package is here, check it out:
https://github.com/YanWenKun/Comfy3D-WinPortable
