### ISSUE TITLE
cuda error      Comfy3D  not working

### ISSUE THREAD

**Issue by eflin1** [YanWenKun/ComfyUI-Windows-Portable#38]
based on your latest release [2024/11/07]

On installing the package i got a "Warn!: Cannot import C:\ComfyUI_Windows_portable_AA\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]"

and

Warn!: C:\ComfyUI_Windows_portable_AA\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(

C:\ComfyUI_Windows_portable_AA\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py:38: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)

C:\ComfyUI_Windows_portable_AA\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Gen_3D_Modules\TriplaneGaussian\utils\ops.py:44: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @custom_bwd

my setup  
Total VRAM 12282 MB, total RAM 65277 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM

----

I, m not a programmer   , and this is  took me a whole day,   

btw I placed your  ComfyUI-3D-Pack\_Pre_Builds  into the custom nodes /ComfyUI-3D-Pack/_Pre_Builds  as a new folder
labeled "_Build_Wheels"  and within that one wheel  folder "_Wheels_win_py312_torch2.5.1_cu124"

**Comment by YanWenKun** [comment]
I see it's about `TriplaneGaussian`, I'm trying to build a retro-package to run it (in less than one year and it's nearly deprecated, so fast the AI goes...).

But before that, based on the info from other issues, I suggest trying the [older release](https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.9).
