### ISSUE TITLE
Cant Update Comfyui

### ISSUE THREAD

**Issue by angomania** [YanWenKun/ComfyUI-Windows-Portable#4]
Hello, I cant update the 2024/05/19 version with PyTorch 2.3.0 and xFormers 0.0.26.post1 and got this error if I try to update from the manager:

Update ComfyUI
Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v -- origin
  stderr: 'error: Could not read 98f828fad98643d4f8f31e355cc79a1fd42e1bb8
error: Could not read 98f828fad98643d4f8f31e355cc79a1fd42e1bb8
error: Could not read 98f828fad98643d4f8f31e355cc79a1fd42e1bb8
error: Could not read 98f828fad98643d4f8f31e355cc79a1fd42e1bb8
fatal: refusing to merge unrelated histories'
CUSTOM NODE PULL: Fail
Install: pip packages
[ComfyUI-Manager] skip black listed pip installation: 'torch'
[ComfyUI-Manager] skip black listed pip installation: 'torchsde'
[ComfyUI-Manager] skip black listed pip installation: 'torchvision'

If I try to update with update_comfyui.bat I got this error:

Traceback (most recent call last):
  File "t:\!TMP\ComfyUI (YanWenKun)\update\update.py", line 69, in <module>
    pull(repo)
  File "t:\!TMP\ComfyUI (YanWenKun)\update\update.py", line 13, in pull
    merge_result, _ = repo.merge_analysis(remote_master_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pygit2.GitError: object not found - no match for id (98f828fad98643d4f8f31e355cc79a1fd42e1bb8)

Could you please make a package without the 3D-Pack?

**Comment by YanWenKun** [comment]
It's a git problem, not related to 3D-Pack.
If you know how to use command line, you can simply fix it by:
```
git reset --hard origin/master
```

Or just download the latest package, the most straight-forward way.

If you don't want 3D-Pack, just delete it in `custom_nodes`. Its dependencies have no conflict with other custom nodes.

The newer version of PyTorch has minor performance gain for most GPUs. I would suggest using Linux for a significant I/O uplift.
If you still want a No-3D-Pack one, fork this repo and remind me, I'll make a PR on it.
