### ISSUE TITLE
Can't see manager? 

### ISSUE THREAD

**Issue by karl0ss** [YanWenKun/ComfyUI-Windows-Portable#40]
Loaded via `run_nvidia_gpu` ui is open and working ok, but I don't see manager anywhere?
![image](https://github.com/user-attachments/assets/18772efd-41dc-4170-9d90-37341d1ef362)

**Comment by YanWenKun** [comment]
By default the icon should be located at top-right corner. Not sure what happend. If a reinstall is not working, paste the log here and let's find the cause.

**Comment by YanWenKun** [comment]
The new release is here, check it out:
https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases

**Comment by derhuebiii** [comment]
Unfortunately I got the same problem. The reason I took your version was the included manager :)

Here is the log file:

> Failed to execute startup-script: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / Failed to initialize: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh(<full-path-to-git-executable>)
> 
> All git commands will error until this is rectified.
> 
> This initial message can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|silent|none|n|0: for no message or exception
>     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
>     - error|e|exception|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet
> [2024-12-14 23:42:23.324] 
> [2024-12-14 23:42:23.355] 
> Prestartup times for custom nodes:
> [2024-12-14 23:42:23.355]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
> [2024-12-14 23:42:23.355]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
> [2024-12-14 23:42:23.355]    4.9 seconds (PRESTARTUP FAILED): C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
> [2024-12-14 23:42:23.355] 
> Total VRAM 6144 MB, total RAM 32240 MB
> [2024-12-14 23:42:38.922] pytorch version: 2.5.1+cu124
> [2024-12-14 23:42:51.627] xformers version: 0.0.28.post3
> [2024-12-14 23:42:51.627] Set vram state to: NORMAL_VRAM
> [2024-12-14 23:42:51.627] Device: cuda:0 NVIDIA RTX A3000 Laptop GPU : cudaMallocAsync
> [2024-12-14 23:42:53.527] Using xformers cross attention
> [2024-12-14 23:43:03.824] [Prompt Server] web root: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\web
> [2024-12-14 23:43:14.909] NumExpr defaulting to 16 threads.
> [2024-12-14 23:43:19.977] [AnimateDiffEvo] - [0;31mERROR[0m - No motion models found. Please download one and place in: ['C:\\Users\\XXXXX\\Documents\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'C:\\Users\\XXXXX\\Documents\\ComfyUI\\ComfyUI\\models\\animatediff_models']
> [2024-12-14 23:43:20.683] [Crystools [0;32mINFO[0m] Crystools version: 1.21.0
> [2024-12-14 23:43:20.730] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools\nodes\image.py:350: SyntaxWarning: invalid escape sequence '\/'
>   "Description": "More info: https:\/\/www.instagram.com\/crystian.ia", # "\/" is for escape / on json
> [2024-12-14 23:43:20.996] [Crystools [0;32mINFO[0m] CPU: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz - Arch: AMD64 - OS: Windows 11
> [2024-12-14 23:43:20.996] [Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
> [2024-12-14 23:43:20.996] [Crystools [0;32mINFO[0m] GPU/s:
> [2024-12-14 23:43:21.012] [Crystools [0;32mINFO[0m] 0) NVIDIA RTX A3000 Laptop GPU
> [2024-12-14 23:43:21.012] [Crystools [0;32mINFO[0m] NVIDIA Driver: 538.18
> [2024-12-14 23:43:21.248] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\translate.py:188: SyntaxWarning: invalid escape sequence '\s'
>   grammar = """
> [2024-12-14 23:43:22.127] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\wildcards.py:171: SyntaxWarning: invalid escape sequence '\+'
>   subpattern = keyword.replace('*', '.*').replace('+','\+')
> [2024-12-14 23:43:22.630] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py:1731: SyntaxWarning: invalid escape sequence '\o'
>   if output_path.endswith("ComfyUI/output") or output_path.endswith("ComfyUI\output"):
> [2024-12-14 23:43:22.677] [34m[ComfyUI-Easy-Use] server: [0mv1.2.6 [92mLoaded[0m
> [2024-12-14 23:43:22.677] [34m[ComfyUI-Easy-Use] web root: [0mC:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 [92mLoaded[0m
> [2024-12-14 23:43:23.101] ### Loading: ComfyUI-Impact-Pack (V8.0.1)
> [2024-12-14 23:43:23.242] [WARN] ComfyUI-Impact-Pack: custom_wildcards path not found: D:\a\ComfyUI-Windows-Portable\ComfyUI-Windows-Portable\builder\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\custom_wildcards. Using default path.
> [2024-12-14 23:43:23.650] [Impact Pack] Wildcards loading done.
> [2024-12-14 23:43:23.697] ### Loading: ComfyUI-Impact-Subpack (V1.0)
> [2024-12-14 23:43:28.720] ### Loading: ComfyUI-Inspire-Pack (V1.9)
> [2024-12-14 23:43:29.018] Total VRAM 6144 MB, total RAM 32240 MB
> [2024-12-14 23:43:29.018] pytorch version: 2.5.1+cu124
> [2024-12-14 23:43:29.018] xformers version: 0.0.28.post3
> [2024-12-14 23:43:29.018] Set vram state to: NORMAL_VRAM
> [2024-12-14 23:43:29.018] Device: cuda:0 NVIDIA RTX A3000 Laptop GPU : cudaMallocAsync
> [2024-12-14 23:43:29.285] Traceback (most recent call last):
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\git\__init__.py", line 296, in <module>
>     refresh()
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\git\__init__.py", line 287, in refresh
>     if not Git.refresh(path=path):
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\git\cmd.py", line 631, in refresh
>     raise ImportError(err)
> ImportError: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh(<full-path-to-git-executable>)
> 
> All git commands will error until this is rectified.
> 
> This initial message can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|silent|none|n|0: for no message or exception
>     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
>     - error|e|exception|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\nodes.py", line 2037, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 8, in <module>
>     import manager_server
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 13, in <module>
>     import git
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\git\__init__.py", line 298, in <module>
>     raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
> ImportError: Failed to initialize: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh(<full-path-to-git-executable>)
> 
> All git commands will error until this is rectified.
> 
> This initial message can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|silent|none|n|0: for no message or exception
>     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
>     - error|e|exception|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet
> 
> 
> [2024-12-14 23:43:29.285] Cannot import C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: Failed to initialize: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh(<full-path-to-git-executable>)
> 
> All git commands will error until this is rectified.
> 
> This initial message can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|silent|none|n|0: for no message or exception
>     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
>     - error|e|exception|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet
> 
> [2024-12-14 23:43:29.693] Traceback (most recent call last):
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\nodes.py", line 2037, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
>     from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
>     from insightface.app.common import Face
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\__init__.py", line 16, in <module>
>     from . import model_zoo
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
>     from .model_zoo import get_model
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
>     from .arcface_onnx import *
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
>     import onnx
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\onnx\__init__.py", line 77, in <module>
>     from onnx.onnx_cpp2py_export import ONNX_ML
> ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
> 
> [2024-12-14 23:43:29.693] Cannot import C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
> [2024-12-14 23:43:30.211] ComfyUI found: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI
> [2024-12-14 23:43:30.211] 'C:\Users\XXXXX\Documents\ComfyUI\ComfyUI' added to sys.path
> [2024-12-14 23:43:32.237] (pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
> [2024-12-14 23:43:32.237] (pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
> [2024-12-14 23:43:32.300] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_list.py:383: SyntaxWarning: invalid escape sequence '\W'
>   "optional": {"folder_path": ("STRING", {"default": "C:\Windows\Fonts", "multiline": False}),
> [2024-12-14 23:43:32.300] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_list.py:393: SyntaxWarning: invalid escape sequence '\W'
>   def make_list(self, source_folder, start_index, max_rows, folder_path="C:\Windows\Fonts"):
> [2024-12-14 23:43:32.379] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\nodes\nodes_xygrid.py:256: SyntaxWarning: invalid escape sequence '\R'
>   resolved_font_path = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "fonts\Roboto-Regular.ttf")
> [2024-12-14 23:43:32.646] ------------------------------------------
> [2024-12-14 23:43:32.646] [34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
> [2024-12-14 23:43:32.646] ------------------------------------------
> [2024-12-14 23:43:32.646] ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
> [2024-12-14 23:43:32.646] ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
> [2024-12-14 23:43:32.646] ------------------------------------------
> [2024-12-14 23:43:32.693] [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
> [2024-12-14 23:43:32.693] [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
> [2024-12-14 23:43:32.693] [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
> [2024-12-14 23:43:32.976] DWPose: Onnxruntime with acceleration providers detected
> [2024-12-14 23:43:33.305] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials\conditioning.py:231: SyntaxWarning: invalid escape sequence '\.'
>   """
> [2024-12-14 23:43:33.400] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py:19: SyntaxWarning: invalid escape sequence '\e'
>   print('Making the "web\extensions\FizzleDorf" folder')
> [2024-12-14 23:43:33.478] [34mFizzleDorf Custom Nodes: [92mLoaded[0m
> [2024-12-14 23:43:33.541] Traceback (most recent call last):
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\nodes.py", line 2037, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
>     from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 13, in <module>
>     from insightface.app import FaceAnalysis
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\__init__.py", line 16, in <module>
>     from . import model_zoo
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
>     from .model_zoo import get_model
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
>     from .arcface_onnx import *
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
>     import onnx
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\onnx\__init__.py", line 77, in <module>
>     from onnx.onnx_cpp2py_export import ONNX_ML
> ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
> 
> [2024-12-14 23:43:33.541] Cannot import C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
> [2024-12-14 23:43:35.723] C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
>   warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
> [2024-12-14 23:43:35.738] C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\timm\models\registry.py:4: FutureWarning: Importing from timm.models.registry is deprecated, please import via timm.models
>   warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.models", FutureWarning)
> [2024-12-14 23:43:36.492] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything\local_groundingdino\models\GroundingDINO\utils.py:59: SyntaxWarning: invalid escape sequence '\s'
>   """
> [2024-12-14 23:43:36.571] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\text_processing\prompt_parser.py:406: SyntaxWarning: invalid escape sequence '\('
>   """
> [2024-12-14 23:43:37.637] [36;20m[comfy_mtb] | INFO -> loaded [96m88[0m nodes successfuly[0m
> [2024-12-14 23:43:37.653] [36;20m[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.[0m
> [2024-12-14 23:43:38.077] 
> [36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m
> [2024-12-14 23:43:38.218] Traceback (most recent call last):
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\nodes.py", line 2037, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\PuLID_ComfyUI\__init__.py", line 1, in <module>
>     from .pulid import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
>   File "C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\PuLID_ComfyUI\pulid.py", line 9, in <module>
>     from insightface.app import FaceAnalysis
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\__init__.py", line 16, in <module>
>     from . import model_zoo
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
>     from .model_zoo import get_model
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
>     from .arcface_onnx import *
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
>     import onnx
>   File "C:\Users\XXXXX\Documents\ComfyUI\python_embeded\Lib\site-packages\onnx\__init__.py", line 77, in <module>
>     from onnx.onnx_cpp2py_export import ONNX_ML
> ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
> 
> [2024-12-14 23:43:38.218] Cannot import C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\PuLID_ComfyUI module for custom nodes: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
> [2024-12-14 23:43:38.406] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy\py\power_prompt_utils.py:11: SyntaxWarning: invalid escape sequence '\d'
>   pattern = '<lora:([^:>]*?)(?::(-?\d*(?:\.\d*)?))?>'
> [2024-12-14 23:43:38.500] 
> [2024-12-14 23:43:38.500] [92m[rgthree-comfy] Loaded 42 magnificent nodes. 🎉[00m
> [2024-12-14 23:43:38.500] 
> [2024-12-14 23:43:38.704] C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py:7352: SyntaxWarning: invalid escape sequence '\o'
>   if output_path.endswith("ComfyUI/output") or output_path.endswith("ComfyUI\output"):
> [2024-12-14 23:43:43.085] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
> [2024-12-14 23:43:43.100] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
> [2024-12-14 23:43:45.017] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m218[0m [32mnodes successfully.[0m
> [2024-12-14 23:43:45.017] 
> 	[3m[93m"Art is the bridge that connects imagination to reality."[0m[3m - Unknown[0m
> [2024-12-14 23:43:45.017] 
> [2024-12-14 23:43:45.048] 
> Import times for custom nodes:
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools-save
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Image-Selector
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\sd-dynamic-thresholding
> [2024-12-14 23:43:45.048]    0.0 seconds (IMPORT FAILED): C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\PuLID_ComfyUI
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
> [2024-12-14 23:43:45.048]    0.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui-portrait-master
> [2024-12-14 23:43:45.048]    0.0 seconds (IMPORT FAILED): C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
> [2024-12-14 23:43:45.048]    0.1 seconds (IMPORT FAILED): C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID
> [2024-12-14 23:43:45.048]    0.1 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
> [2024-12-14 23:43:45.048]    0.1 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
> [2024-12-14 23:43:45.048]    0.1 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
> [2024-12-14 23:43:45.048]    0.1 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes
> [2024-12-14 23:43:45.048]    0.1 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\mikey_nodes
> [2024-12-14 23:43:45.048]    0.1 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
> [2024-12-14 23:43:45.048]    0.1 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
> [2024-12-14 23:43:45.048]    0.1 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
> [2024-12-14 23:43:45.048]    0.2 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-GGUF
> [2024-12-14 23:43:45.048]    0.2 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
> [2024-12-14 23:43:45.048]    0.2 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
> [2024-12-14 23:43:45.048]    0.2 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
> [2024-12-14 23:43:45.048]    0.2 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
> [2024-12-14 23:43:45.048]    0.2 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
> [2024-12-14 23:43:45.048]    0.2 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes
> [2024-12-14 23:43:45.048]    0.3 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
> [2024-12-14 23:43:45.048]    0.3 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
> [2024-12-14 23:43:45.048]    0.4 seconds (IMPORT FAILED): C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
> [2024-12-14 23:43:45.048]    0.4 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
> [2024-12-14 23:43:45.048]    0.5 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
> [2024-12-14 23:43:45.048]    0.5 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-to-Python-Extension
> [2024-12-14 23:43:45.048]    0.6 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
> [2024-12-14 23:43:45.048]    0.6 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
> [2024-12-14 23:43:45.048]    0.8 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfy_mtb
> [2024-12-14 23:43:45.048]    1.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools
> [2024-12-14 23:43:45.048]    1.5 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
> [2024-12-14 23:43:45.048]    2.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
> [2024-12-14 23:43:45.048]    2.9 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
> [2024-12-14 23:43:45.048]    5.0 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
> [2024-12-14 23:43:45.048]    6.5 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
> [2024-12-14 23:43:45.048]    7.7 seconds: C:\Users\XXXXX\Documents\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved
> [2024-12-14 23:43:45.048] 
> [2024-12-14 23:43:45.080] Starting server
> 
> [2024-12-14 23:43:45.080] To see the GUI go to: http://127.0.0.1:8188
>

**Comment by YanWenKun** [comment]
@karl0ss @derhuebiii I see...

Here's how to fix it:

Install [Git for Windows](https://git-scm.com/download/win). Default settings is OK.

I'll update the README.

**Comment by karl0ss** [comment]
Sorry about the lack of response, but @YanWenKun  that did fix it :)

**Comment by karl0ss** [comment]
I doubt it, @derhuebiii could you try - https://github.com/sheabunge/GitPortable - ?
