### ISSUE TITLE
Help me please install custom node

### ISSUE THREAD

**Issue by Falkonar** [YanWenKun/ComfyUI-Windows-Portable#44]
https://github.com/lujiazho/ComfyUI-CatvtonFluxWrapper

Is it possible to install this node? For some reason it not loading. Thank you for your effort ! 🙏🙏🙏

**Comment by YanWenKun** [comment]
Just git clone it, no additional deps needed.

Open Git Bash in `custom_nodes`, paste:

```
git clone https://github.com/lujiazho/ComfyUI-CatvtonFluxWrapper.git
```

Then start ComfyUI.
