### ISSUE TITLE
No workflows

### ISSUE THREAD

**Issue by vasilybodnar** [YanWenKun/ComfyUI-Windows-Portable#45]
When opening any worflows, nothing appears in browser window...
![Screenshot 2024-12-27 121811](https://github.com/user-attachments/assets/493a4ca4-3110-4b77-9f12-074a57c0acca)

**Comment by YanWenKun** [comment]
Try update ComfyUI (using Manager -> update ComfyUI)

**Comment by vasilybodnar** [comment]
![Screenshot 2024-12-27 122659](https://github.com/user-attachments/assets/8d23bac2-c208-408e-8a4c-1f7d80fea165)
It has the latest version

**Comment by YanWenKun** [comment]
In the right-bottom corner, find the "Fit View" button, click it to see if the nodes show.

![fitview](https://github.com/user-attachments/assets/e7627c85-9e6a-4ac1-8cb8-65a956eff059)

**Comment by YanWenKun** [comment]
Also, try open the http://localhost:8188/ in browser's incognito/privacy mode, so it won't have cache in browser.

**Comment by vasilybodnar** [comment]
thank you.
