### ISSUE TITLE
Investigation on nvdiffrast

### ISSUE THREAD

**Issue by YanWenKun** [YanWenKun/ComfyUI-Windows-Portable#6]
https://github.com/YanWenKun/ComfyUI-Windows-Portable/issues/5#issuecomment-2229780292
https://github.com/YanWenKun/ComfyUI-Docker/issues/42

There might be some issues with `nvdiffrast` loading C/C++ parts. Need Investigation.

**Comment by Falkonar** [comment]
> [#5 (comment)](https://github.com/YanWenKun/ComfyUI-Windows-Portable/issues/5#issuecomment-2229780292) [YanWenKun/ComfyUI-Docker#42](https://github.com/YanWenKun/ComfyUI-Docker/issues/42)
> 
> There might be some issues with `nvdiffrast` loading C/C++ parts. Need Investigation.

The same. This happened on the new PyTorch 2.3.1 version?

**Comment by Falkonar** [comment]
> [#5 (comment)](https://github.com/YanWenKun/ComfyUI-Windows-Portable/issues/5#issuecomment-2229780292) [YanWenKun/ComfyUI-Docker#42](https://github.com/YanWenKun/ComfyUI-Docker/issues/42)
> 
> There might be some issues with `nvdiffrast` loading C/C++ parts. Need Investigation.

I've found solution. You need CUDA Toolkit 12.1. If not help, then check variables path
