### ISSUE TITLE
Use of Comfyui-3D-Pack

### ISSUE THREAD

**Issue by clemecleme** [YanWenKun/ComfyUI-Windows-Portable#7]
Hey there, 
Thanks a lot for your work, so helpful!
I'm trying to use Comfyui-3D-Pack, which is well installed, but I'm always stuck at the ExplicitTarget Mesh Optimization node level: Comfyui crashes - and Event viewer reports a problem with matplotlib.
Not sure what is causing the problem. I've tried many uninstall/desinstall (comfyui, 3D-Pack, matplotlib) but the problem still occurs. Thank to your work, I realised it might be a compatibility issue - tried to downgrade PyTorch to 2.2.2, but I have to update comfyui-3D-Pack to access custom-nodes and it goes back to torch 2.3.0 because of pre-weels.

Any suggestion would be awesome! Thanks a lot

[
![ComfyUI_crash](https://github.com/user-attachments/assets/e1a575c2-d8f0-4a67-878a-e19536b459e3)
![Eventviewer_error](https://github.com/user-attachments/assets/79300687-a925-4b70-9717-a81e2f7379b9)
](url)

**Comment by zafirexd** [comment]
![image](https://github.com/user-attachments/assets/4aff279a-a1c6-41d4-a898-34f8e6f2c176)
all its working perfectly in f3cbd66 commit 
https://github.com/MrForExample/ComfyUI-3D-Pack/tree/f3cbd66020d109cbfd4c708e9d989245af752768
i downloaded as zip and extract as manual custom node install in this comfy instance https://github.com/YanWenKun/ComfyUI-Windows-Portable/releases/tag/v3.9
Anyway, CharaGen is working well on update, so i start to manage the both instances, 
I have win10 and rtx 3060 12Gb.
So for charagen cut the process and save all the images,
![image](https://github.com/user-attachments/assets/8def84e7-82f3-4e04-8b23-a2549d2b89e2)
Then load them in with examples/unique 3d/3_Mesh_Reconstruction.json workflow in the commit instance
![image](https://github.com/user-attachments/assets/fe690bda-1809-48ca-bb09-964972d71a7d)
well......its working xD!, CharaGen its better for anime characters.
@MrForExample thanks for the support.

_Originally posted by @zafirexd in https://github.com/MrForExample/ComfyUI-3D-Pack/issues/197#issuecomment-2226796851_

**Comment by clemecleme** [comment]
thanks for your answer! Actually I came here because of your answer on the other Github ahahah
Good to know, when you say installed 3D-Pack manually you mean with Conda? 
I'm pretty interested by Unique3D workflows, did you managed to use it? thanks!
