### ISSUE TITLE
Embedded python scripts directory not on path

### ISSUE THREAD

**Issue by RobertVorback** [YanWenKun/ComfyUI-Windows-Portable#8]
I get the following warning from the console, in Windows 11, 

WARNING: The script deep.exe is installed in 'E:\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
[!]   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
 Successfully installed deepdiff-7.0.1 ordered-set-4.1.0

I assume adding the directory to my system PATH will not have any effect for ComfyUI_windows_portable
How do I fix this for the python_embedded ?

**Comment by YanWenKun** [comment]
Just edit `run_nvidia_gpu.bat`, add this line as the first line:

```
set PATH=%PATH%;E:\ComfyUI_windows_portable\python_embeded\Scripts\
```

**Comment by RobertVorback** [comment]
That solved the issue.
Thank you Yan
