### ISSUE TITLE
ComfyUI_Windows_portable_cu121.7z.001 ERROR

### ISSUE THREAD

**Issue by lavibeats** [YanWenKun/ComfyUI-Windows-Portable#9]
this file has issue (update 2024/07/23)
![errormessage-1](https://github.com/user-attachments/assets/897b8ca2-ed31-4061-9ba7-a5485d0ef8bc)

**Comment by YanWenKun** [comment]
Use 7-zip:
https://www.7-zip.org/download.html

**Comment by lavibeats** [comment]
no luck


![ssss](https://github.com/user-attachments/assets/4c808054-bbe2-4fe5-8527-fe74a94a9b05)

**Comment by YanWenKun** [comment]
"Unexpected end of data" could be missing files. Download all files (.7z.001, .7z.002, .7z.003) before open.

![图片](https://github.com/user-attachments/assets/d4160c7d-b17c-4c6a-a7f5-3131b5cd3c0f)

![图片](https://github.com/user-attachments/assets/bdd29126-4e3d-43d5-8c6b-64b4be7d31dd)

PS. I just published two new versions, check if they meet your need

**Comment by panpan123429** [comment]
![Image](https://github.com/user-attachments/assets/b55bb0cd-2ef2-4492-953e-b56a93091daf)

压缩包里不是文件夹，解压出来无效的文件
